name: Deployment Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.    
      ref:  
        type: string
        required: true
        description: The tag or SHA to checkout.

env:
  GCP_PROJECT_ID: "hader-poc-001"
  REGION: "us-central1"
  ARTIFACT_REPO: "cloud-run-source-deploy"
  SERVICE_NAME: "gha-run-003"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "ENV: ${{ inputs.environment }} - ${{ vars.TEST }}"