name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ vars.GCP_SA_WIF_PROVIDER }}'
          service_account: '${{ vars.GCP_SA_WIF_SA }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: function-test
          region: us-central1
          source: run-src/
          flags: '--port=8081'