name: Deploy Cloud Functions
run-name: 🚀 ${{ github.actor }} is deploying all cloud functions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write'
      
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ vars.GCP_SA_WIF_PROVIDER }}'
          service_account: '${{ vars.GCP_SA_WIF_SA }}'
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: gha-run
          region: us-central1
          # NOTE: If required, update to the appropriate source folder
          source: run-src/