name: Main Workflow to Deploy to Cloud Run
on:
  push:
    branches: [develop, stage, main]

jobs: 
  dev:
    name: develop
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/deploy-run-multienv.yml
    permissions:
        contents: 'read'
        id-token: 'write'    
    with: 
      environment: dev
      src_path: src
    secrets: inherit
  stage:
    if: ${{ github.ref == 'refs/heads/stage' || github.base_ref == 'stage' }}
    uses: ./.github/workflows/deploy-run-multienv.yml
    permissions:
        contents: 'read'
        id-token: 'write'    
    with: 
      environment: stage
      src_path: src
    secrets: inherit
  prod: 
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/deploy-run-multienv.yml
    permissions:
        contents: 'read'
        id-token: 'write'    
    with:
      environment: prod
      src_path: src
    secrets: inherit