name: Main Workflow to Deploy to Cloud Run
on:
  push:
    branches: [develop, stage, main]

jobs:
  call-reusable-workflow:
    uses: hader-google/main-cicd/.github/workflows/main.yml@main
    permissions:
      contents: 'read'
      id-token: 'write'   